/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
WARN: Not all rootspaces examined because their weights are too small. Metrics for omitted rootspaces are set to -1. Set print_all_but=-1 to ensure all rootspaces are examined.
Traceback (most recent call last):
  File "/project/lgagliardi/valayagarawal/lasscf/mof_nodes/Fe_Fe_Fe/production/15_16/lassi.py", line 46, in <module>
    np.save('r1_n5_ct/ci1',ci1)
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/numpy/lib/npyio.py", line 545, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 182) + inhomogeneous part.
Command exited with non-zero status 1
	Command being timed: "python lassi.py"
	User time (seconds): 33754.03
	System time (seconds): 25053.30
	Percent of CPU this job got: 403%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 4:03:09
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 25398392
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 7322621
	Voluntary context switches: 1091251
	Involuntary context switches: 930649246
	Swaps: 0
	File system inputs: 0
	File system outputs: 26496
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
